#! /bin/bash

if [ ! -d "venv" ]; then
    echo Virtual Environment not found. Creating...;
    /usr/bin/python3 -m venv venv;
    echo DONE;
fi

source "$(pwd)/venv/bin/activate";

python3 -m run $1 $2;

deactivate;
